server:
  port: 8004
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: msm
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 10.211.55.3
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
aliyun:
  vod:
    file:
      keyid: LTAI4FkydZnNUWdxQw8AebAHe
      keysecret: CvyrtbK2dCQlovqElwL3ZEaA3fHdrPr

mybatis-plus:
  mapper-locations: classpath:org/online/edu/mapper/xml/*xml
mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    io.swagger: ERROR
    com.filter.LoggingFilter: DEBUG